apiVersion: v1
kind: ServiceAccount
metadata:
  name: hpa-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hpa-role
rules:
  # Read pods and metrics
  - apiGroups: [""]
    resources: ["pods", "pods/metrics"]
    verbs: ["get", "list", "watch"]
  # Update replicas in deployments or rollouts
  - apiGroups: ["apps", "argoproj.io"]
    resources: ["deployments", "rollouts"]
    verbs: ["get", "list", "watch", "update"]
    
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hpa-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hpa-role
subjects:
  - kind: ServiceAccount
    name: hpa-sa
    namespace: default
