# 🔹 Analysis Template for Success Rate
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate-check
spec:
  metrics:
    - name: success-rate
      interval: 30s
      successCondition: result[0] >= 0.95   # 95% success
      failureLimit: 3
      provider:
        prometheus:
          address: http://prometheus.default.svc.cluster.local:9090
          query: |
            sum(rate(http_requests_total{service="{{args.service-name}}",status=~"2.."}[1m])) 
            / 
            sum(rate(http_requests_total{service="{{args.service-name}}"}[1m]))

---
# 🔹 Analysis Template for Latency
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: latency-check
spec:
  metrics:
    - name: latency
      interval: 1m
      successCondition: result[0] < 0.5   # less than 0.5 sec
      failureLimit: 2
      provider:
        prometheus:
          address: http://prometheus.default.svc.cluster.local:9090
          query: |
            histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{service="hotstar-canary"}[1m])) by (le))
